### 1.Explain the difference between a Python list and a NumPy array in terms of memory usage and performance. Then, write a program that creates both and performs element-wise multiplication.
    Ans: Python list usuage is more compared to NumPy Array, as Python list stores references to objects,
         can store mixed types whereas Numpy Array stores elements in contiguous memory, usually stores same
         data type.

In [9]:
import numpy as np
ls = [1,2,3,4,5]
a = np.array(ls)
b=np.array([2,4,6,8,2])
result=a*b
print("this is my list", ls)
print("type of array",type(ls))
print("this is ",a)
print("type of array",type(a))
print("Element wise multiplication : ",result)
print(type(result))


this is my list [1, 2, 3, 4, 5]
type of array <class 'list'>
this is  [1 2 3 4 5]
type of array <class 'numpy.ndarray'>
Element wise multiplication :  [ 2  8 18 32 10]
<class 'numpy.ndarray'>


### 2.What is broadcasting in NumPy? Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain    how NumPy applies the operation internally.
    Ans: Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically 
         expanding the smaller array.
   


In [10]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([1,2,3])
result=x+y
result

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [11]:
print("Result by using the broadcasting : ",result)

Result by using the broadcasting :  [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


### 3.What are missing values in Pandas and how are they represented? Create a DataFrame with missing values and      write code to:
###   •Detect missing values
###   •Replace them with the column mean Explain each step.
    Ans: Missing values represent absent data, represented by: NaN and None.

In [12]:
import pandas as pd
dt = {
    "Name": ["Ajay", "Anjali", "Harsh", "Priya"],
    "Math": [82, np.nan, 70, 95],
    "Science": [88, 65, np.nan, 90]
}
data = pd.DataFrame(dt)
print(data)

     Name  Math  Science
0    Ajay  82.0     88.0
1  Anjali   NaN     65.0
2   Harsh  70.0      NaN
3   Priya  95.0     90.0


In [13]:
data["Math"] = data["Math"].fillna(data["Math"].mean())
data["Science"] = data["Science"].fillna(data["Science"].mean())
data

Name       Math  Science
0    Ajay  82.000000     88.0
1  Anjali  82.333333     65.0
2   Harsh  70.000000     81.0
3   Priya  95.000000     90.0

### 4.Explain boolean indexing in NumPy or Pandas.            Create a DataFrame with at least 5 columns and filter rows based on two conditions using logical operators. Explain how filtering works internally.
    Ans: Boolean indexing is used for filter data in pandas to specified condition 

In [18]:
data={'Name': ['harsh', 'hemant', 'ayush', 'mohit', 'aman'],
    'Age': [21, 22, 22, 21, 23],
    'Salary': [50000, 80000, 120000, 90000, 95000],
    'Dept': ['EE', 'CSE', 'CSE', 'CSE', 'ME']
}       
df=pd.DataFrame(data)
filter_data=df[(df['Salary']>60000) & (df['Dept']=='CSE')]
print(f"The Filter data is:\n{filter_data}")

The Filter data is:
     Name  Age  Salary Dept
1  hemant   22   80000  CSE
2   ayush   22  120000  CSE
3   mohit   21   90000  CSE


### 5.What is the purpose of the groupby() function in Pandas? Create a DataFrame with categorical data (e.g., department & salary) and calculate the average salary per department using groupby(). Explain the output.
    Ans: Groupby() groups data based on categorical columns and applies aggregation functions.

In [14]:
data = pd.DataFrame({
    'Department': ['accounts', 'Teaching', 'drivers', 'Transport', 'adminstrator'],
    'Salary': [750000, 40000, 20000, 80000, 90000]
})
avg_salary = data.groupby('Department')['Salary'].mean()
print(f"The average of salary:{avg_salary}")

The average of salary:Department
Teaching         40000.0
Transport        80000.0
accounts        750000.0
adminstrator     90000.0
drivers          20000.0
Name: Salary, dtype: float64
